### ISSUE TITLE
Add a --max-snapshots option (deletes any snapshots older than --max-snapshots)

### ISSUE THREAD

**Issue by skurudo** [seanh/snapshotter#22]
Hello.

I see option --min-snapshots, but how can I set max-snapshots or control how many snapshots can be on remote drive?

**Comment by seanh** [comment]
There's no such option. The intended usage is that it keeps adding snapshots until the volume you're backing up to is full, then it'll start deleting the oldest snapshots to make way for new ones (you can of course delete old snapshots manually whenever you want).

I'd be happy to add a --max-snapshots option though, should be easy enough. Pull request welcome!

**Comment by skurudo** [comment]
Thanks for your answer, but I don't know how ;-(

How script know, when volume full? Where trigger/check  for that in code?

**Comment by seanh** [comment]
The `_rsync()` function raises `NoSpaceLeftOnDeviceError` if rsync fails because it doesn't have enough space to make the snapshot. This `while` loop catches the error and deletes the oldest snapshot, before iterating again: https://github.com/seanh/snapshotter/blob/master/snapshotter/snapshotter.py#L368

I think the place to add a max_snapshots option would be in the snapshot() function. This could call `_ls_snapshots()` to get the list of snapshots, and if there are more than max_snapshots of them then call `_rm()` as many times as necessary to remove the oldest ones.

You'd then need to add a `--max-snapshots` command-line argument, which can be done by copying the min-snapshots one.

**Comment by Lightjohn** [comment]
Hello, I found your project and it seems nice. But one of the first questions was the max-snapshots option.
But as the question is still open, I would like to ask if there was something new ? If not I will try to do it.

**Comment by seanh** [comment]
Hi @Lightjohn, I intend to add the `--max-snapshots` option one day, the next time I get a couple of days to work on snapshotter, but I have no idea when that might be. In the meantime a pull request to add the feature would be very welcome :)

**Comment by Lightjohn** [comment]
Ok I'll look at it soon, but as your code is clear and concise it may be fast. What should I do when `-max-snapshots` is inconsistent with `-min-snapshots` ?

**Comment by seanh** [comment]
Good question. I think it might be good to raise an exception and crash with an error message telling the user what went wrong.

Looking forward to seeing the code!

**Comment by seanh** [comment]
Done, https://github.com/seanh/snapshotter/pull/35

**Comment by seanh** [comment]
@skurudo @Lightjohn `--max-snapshots` should now work if you upgrade to the latest version of snapshotter (`sudo pip install --upgrade snapshotter`)
